name: flutter_app
description: "EngagePoint App for ITMDA Group S11"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  googleapis_auth: ^1.4.1
  jose: ^0.3.5
  


  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.2 
  firebase_analytics: ^11.6.0
  shared_preferences: ^2.2.3
  intl: ^0.18.1
  firebase_storage: ^12.4.10
  firebase_messaging: ^15.2.10
  flutter_native_splash: ^2.4.0
  url_launcher: ^6.2.6
  http: ^1.5.0
  image_picker: ^1.2.0
  flutter_timezone: ^5.0.0
  fl_chart: ^0.68.0
  permission_handler: ^12.0.1
  file_saver: ^0.3.1
  pdf: ^3.11.3
  mime_type: ^1.0.1
  mime: ^2.0.0
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  dio: ^5.9.0
  printing: ^5.14.2

  
  # http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  

flutter:
  uses-material-design: true


  assets:
    - assets/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"


flutter_native_splash:
  color: "#FFFFFF" 
  image: assets/splash_logo.png
  android: true
  ios: true
  