name: flutter_app
description: "EngagePoint App for ITMDA Group S11"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0' # It's better to use a range

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.2 
  shared_preferences: ^2.2.3
  intl: ^0.18.1
  firebase_storage: ^12.4.10
  image_picker: ^1.1.2  
  firebase_messaging: ^15.2.10
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 # Moved to dev_dependencies

flutter:
  uses-material-design: true

  # THE FIX IS HERE: Correct indentation and folder declaration
  assets:
    - assets/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

# THE FIX IS HERE: This section should not be indented, and the color code is corrected.
flutter_native_splash:
  color: "#FFFFFF" 
  image: assets/splash_logo.png
  android: true
  ios: true
  